Add `rename-job` cmd to `apsisctl`
apsis-scheduler/apsis pull request #341
Opened 2024-07-31 12:21 UTC by LudovicoRighi

Fixes https://github.com/alexhsamuel/apsis/issues/168.

2024-08-01 19:27 UTC, alexhsamuel requested changes
This code in its current form is is too hacky to be a `apsisctl` subcommand.

If you want to keep it in this form, please put it somewhere local to you; it doesn't belong in Apsis.  If you want it in Apsis, please implement it correctly, along these lines:
- Create `apsis.jobs.rename_job(jobs_dir, old_name, new_name)` that returns a `JobsDir`.  This should use the YAML structure correctly, not just a textual substitution.
- Add a `dump_jobs_dir(jobs_dir, path)` to write out an entire directory.
- Add an `apsisctl` subcommand that loads the entire jobs dir, renames the job correctly, checks it, and writes out the jobs dir to a new location.

2024-08-01 19:27 UTC, alexhsamuel commented on python/apsis/ctl.py
> +        new_lines = [line.replace(old_value, new_value) for line in lines]
This is dangerous.  How do you know that `old_value` won't appear in some other context in the YAML source?

The correct way to do this is to look for the job ID in specific places in the YAML structure where you expect job IDs to occur, and change them there.  This brings a maintenance burden, though; you need to update these locations if the job schema changes.

2024-08-01 19:27 UTC, alexhsamuel commented on python/apsis/ctl.py
> +        new_lines = [line.replace(old_value, new_value) for line in lines]
No need to replace by line; you can `str.replace` the entire contents of the file.

2024-08-01 19:27 UTC, alexhsamuel commented on python/apsis/ctl.py
> +        cur_dir = Path.cwd()
Take the job directory explicitly, like `check_jobs` does, rather than assuming CWD.

2024-08-01 19:27 UTC, alexhsamuel commented on python/apsis/ctl.py
> +            logging.warning(f"Please, make sure to be at your jobs dir root to find all dependencies: {cur_dir}")
Why warn and then continue with mutations?

2024-08-01 19:27 UTC, alexhsamuel commented on python/apsis/ctl.py
> +        if cur_dir.name != "jobs":
This may be your local convention, but nothing in Apsis requires that the jobs dir be named `jobs`.

2024-08-01 19:27 UTC, alexhsamuel commented on python/apsis/ctl.py
> +        for root, _, files in os.walk(cur_dir):
There already is functionality to enumerate jobs in a jobdir in `apsis.jobs`.

2024-08-01 19:31 UTC, alexhsamuel commented
BTW the logic as you implemented it is a shell two-liner:
```
$ mv $oldname.yaml $newname.yaml
$ find . -name \*.yaml -exec sed -i "s#$oldname#$newname#g" {} \;
```

2024-08-01 19:36 UTC, alexhsamuel commented
Come to think of it, mutating YAML files is fraught; at the very least, you'll lose comments and whitespace.

I suggest you note the shell two-liner above in your wiki, with an admonition that users run `apsisctl check_jobs` double-check the `git diff` before committing.

2024-08-02 11:51 UTC, LudovicoRighi commented
Thank you for reviewing, Alex.

> Come to think of it, mutating YAML files is fraught; at the very least, you'll lose comments and whitespace.

That's why I decided to use textual substitution in the first place:
- for comments, I saw [`ruamel` library](https://pypi.org/project/ruamel.yaml/) could be used to preserve them (even if at the cost of adding a dependency to that library.)
- but for whitespaces, I haven't really found a solution (if not raw text manipulation)

-------------------------------------------------------------------------------------------------------

>  If you want it in Apsis, please implement it correctly, along these lines:

> This should use the YAML structure correctly, not just a textual substitution.

I'm happy to follow you comments for improving my code; however, as you mentioned, there is not really a clean way to deal with yaml files, while preserving both comment and whitespaces. If you think this is a blocker, I'll close this PR and just add the shell two-liner to our wiki.

2024-08-02 13:31 UTC, alexhsamuel commented
Yes, I would have started with `ruamel_yaml` as well.  I've used it before only with mixed success.  Whether comments/whitespace are a blocker is sort of up to you.  YAML isn't a great format choice for automatic modification, for these reasons.  Comments seem important to me, whitespace less so.

If we can't find a generally correct solution and you'll go with a semi-manual approach, I think good wiki instructions are better.

2024-11-03 22:17 UTC, closed without merging